# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r_binary_packages:
  - R2jags
  - rjags

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - cat DESCRIPTION
  - jags_install || true

bioc_required: yes
use_bioc: yes
